spring.application.name=SpringConsumerAppPubSub

#Provide details for MQ
spring.activemq.user=admin
spring.activemq.password=admin
spring.activemq.broker-url=tcp://localhost:61616

#Pub Sub communication
spring.jms.pub-sub-domain=true

#Destination for topic
my.app.desti-name=my-topic-abc